"""Original score and synthesized (not sampled from recordings) 86 PCM drums."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RATE = 11025
SAMPLE_LEN = 960  # 87 ms; tail returns to digital zero before the next 100 ms step
KEYS = ['Am', 'Bbm', 'Bm', 'Cm', 'C#m', 'Dm', 'Ebm', 'Em', 'Fm', 'F#m', 'Gm', 'G#m']
CHORDS = [(65, 69, 72), (67, 71, 74), (69, 72, 76), (69, 72, 76)]
LEADS = [
    [0, 3, 7, 3, 8, 7, 3, 0, 3, 7, 10, 7, 8, 7, 3, 7],
    [2, 5, 10, 5, 14, 10, 5, 2, 5, 10, 14, 10, 17, 14, 10, 5],
    [12, 7, 3, 7, 14, 12, 7, 3, 15, 14, 12, 7, 19, 15, 14, 12],
    [15, 12, 7, 3, 14, 12, 7, 3, 12, 7, 3, 0, 7, 10, 11, 12],
]


def score():
    rows = []
    for key in range(12):
        for bar in range(4):
            chord = CHORDS[bar]
            for step in range(16):
                lead = 69 + LEADS[bar][step] + key
                bass = chord[0]-24+key+(12 if step % 8 == 6 else 0) if step % 2 == 0 else 255
                arp = chord[(step // 2) % 3] - 12 + key
                # Drum IDs: 0 hat, 1 kick+hat, 2 snare+hat, 3 tom, 4 sweep/crash.
                drum = 2 if step in (4, 12) else 1 if step in (0, 8, 10) else 0
                if bar == 3 and step in (13, 14, 15): drum = 3
                if bar == 0 and step == 0: drum = 4
                rows.append([lead, bass, arp, *(n+key for n in chord), drum])
    return rows


def pcm(kind):
    data = bytearray()
    seed = 0x980186 + kind
    phase = 0.0
    previous_noise = 0.0
    for i in range(SAMPLE_LEN):
        t = i / RATE
        seed = (1664525*seed + 1013904223) & 0xffffffff
        noise = ((seed >> 8) / 8388607.5) - 1
        high = (noise - previous_noise) * .5
        previous_noise = noise
        hat = high * math.exp(-t*95) * .23
        if kind == 0:
            s = hat
        elif kind == 1:
            phase += math.tau * (52 + 140*math.exp(-t*55)) / RATE
            s = math.sin(phase)*math.exp(-t*36)*.78 + hat
        elif kind == 2:
            s = (noise*.60 + math.sin(math.tau*185*t)*.22)*math.exp(-t*44) + hat
        elif kind == 3:
            phase += math.tau * (105 + 120*math.exp(-t*30)) / RATE
            s = math.sin(phase)*math.exp(-t*32)*.65
        else:
            phase += math.tau*(650 + 2100*i/SAMPLE_LEN)/RATE
            s = (high*.48 + math.sin(phase)*.28)*math.exp(-t*27)
        # Smooth attack/final tail, signed 8-bit samples, stereo with gentle pan.
        envelope = min(1, i/12, (SAMPLE_LEN-1-i)/100)
        for gain in ((.85, 1.0) if kind == 0 else (1.0, .88) if kind == 3 else (1.0, 1.0)):
            data.append(round(max(-.98, min(.98, s*envelope*gain))*127) & 255)
    assert data[-2:] == b'\0\0'
    return bytes(data)


def generate():
    lines = ['; Generated by make_music.py. Original score and synthesized PCM.']
    def emit(name, values, directive='db'):
        lines.append(name + ':')
        for i in range(0, len(values), 16):
            lines.append('    '+directive+' '+','.join(map(str, values[i:i+16])))
    fm, ssg = [], []
    for note in range(128):
        frequency = 440 * 2**((note-69)/12)
        block = max(0, min(7, note//12-1))
        fnum = min(2047, round(frequency*144*2**20/(3993600*2**block)))
        fm.append((block << 11) | fnum)
        ssg.append(max(1, min(4095, round(1996800/(16*frequency)))))
    emit('fm_notes', fm, 'dw')
    emit('ssg_notes', ssg, 'dw')
    # FM operator register order is 1,3,2,4. Carrier levels follow algorithm.
    voices = [
        (4, [1, 2, 1, 1], [30, 38, 14, 18], [31]*4, [8]*4, [3]*4, [0x48]*4),
        (0, [1, 1, 1, 1], [32, 36, 28, 14], [31]*4, [8]*4, [4]*4, [0x48]*4),
        (4, [2, 3, 1, 1], [40, 46, 24, 28], [31]*4, [14]*4, [6]*4, [0x68]*4),
    ]
    init = [0x22, 0, 0x27, 0x30]  # LFO off, stop/reset both timers (no IRQs)
    for channel, voice in enumerate(voices):
        algorithm, *groups = voice
        for group, vals in enumerate(groups):
            for operator, val in enumerate(vals):
                init.extend((0x30 + group*16 + operator*4 + channel, val))
        for operator in range(4): init.extend((0x90+operator*4+channel, 0))
        init.extend((0xb0+channel, algorithm | 0x20))
    emit('fm_init_table', init)
    lines.append('FM_INIT_PAIRS equ ($-fm_init_table)/2')
    emit('music_score', [n for row in score() for n in row])
    lines.append('MUSIC_ROWS equ ($-music_score)/7')
    lines.append('pcm_table:')
    for k in range(5): lines.append(f'    dw pcm_{k}, {2*SAMPLE_LEN}')
    for k in range(5): emit(f'pcm_{k}', list(pcm(k)))
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    (ROOT / 'src/music_data.inc').write_text(generate(), encoding='ascii')
    (ROOT / 'build').mkdir(exist_ok=True)
    (ROOT / 'build/score.json').write_text(json.dumps(dict(
        title='Chromatic Orbit', bpm=150, steps_per_beat=4, keys=KEYS,
        progression='bVI-bVII-i-i', bars_per_key=4, rows=score(), pcm_rate=RATE,
        pcm_samples=SAMPLE_LEN), indent=2)+'\n', encoding='utf-8')
