"""Generate a standalone ASW source from the canonical NASM sources.

Only the deliberately small syntax subset used by this project is translated.
No binary blobs or NASM installation are needed to assemble the result.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent


def expand(path):
    result = []
    for line in path.read_text(encoding='utf-8').splitlines():
        include = re.match(r'%include "([^"]+)"', line)
        if include:
            result.extend(expand(ROOT / include[1]))
        else:
            result.append(line)
    return result


def generate():
    result = ['; Generated by src/make_asw.py; standalone ASW 8086 source.',
              '    cpu 8086', '    assume cs:code,ds:code,ss:code,es:nothing']
    scope = 'entry'
    macro = None
    macros = {}
    lines = []
    for line in expand(ROOT / 'roto.asm'):
        if line.startswith('%macro '):
            macro = line.split()[1]
            macros[macro] = []
        elif line.startswith('%endmacro'):
            macro = None
        elif macro:
            macros[macro].append(line)
        elif line.strip() in macros:
            lines.extend(macros[line.strip()])
        else:
            lines.append(line)
    for line in lines:
        code, sep, comment = line.partition(';')
        if re.match(r'\s*(bits|cpu)\b', code):
            continue
        if code.startswith('%if'):
            code = '    if $ > 10000h'
        elif code.startswith('%error'):
            code = '    fatal "COM image exceeds single-segment capacity"'
        elif code.startswith('%endif'):
            code = '    endif'
        label = re.match(r'^([A-Za-z_]\w*)(?=:|\s+(?:db|dw|equ|times)\b)', code)
        if label:
            scope = label[1]
        code = re.sub(r'(?<!\w)\.(\w+)', lambda m: scope + '__' + m[1], code)
        code = re.sub(r'\[(es|cs|ss|ds):([^\]]+)\]', r'\1:[\2]', code)
        code = re.sub(r'\b(byte|word)\s+(?=\[|(?:es|cs|ss|ds):)', r'\1 ptr ', code)
        code = re.sub(r'\btimes\s+(\d+)\s+db\s+0', r'db \1 dup (0)', code)
        # NASM fills alignment gaps with NOP; ASW needs an explicit filler.
        code = re.sub(r'\balign (\d+)\b', r'align \1,90h', code)
        if code and not code[0].isspace() and not label and ':' not in code:
            code = '    ' + code
        result.append(code + (sep + comment if sep else ''))
    return '\n'.join(result) + '\n'


if __name__ == '__main__':
    target = ROOT / 'asw' / 'roto.asm'
    target.parent.mkdir(exist_ok=True)
    target.write_text(generate(), encoding='ascii')
