"""Deterministic integer texture and precomputed 8.8 affine coefficients."""
from pathlib import Path
import math


def texture_pixel(x, y):
    # Repeating bright tiles, dark mortar, inset bevel and a diamond motif.
    tx, ty = x % 32, y % 32
    color = (1, 5, 3, 6)[(x // 32) + 2 * (y // 32)]
    if tx < 2 or ty < 2:
        return 0
    if tx == 2 or ty == 2:
        return 7
    if tx == 31 or ty == 31:
        return 1
    distance = abs(tx - 16) + abs(ty - 16)
    if distance < 6:
        return 7
    if distance < 9:
        return 0
    return color


def generate():
    lines = ['; Generated by make_assets.py. Do not edit.']
    def emit(label, values, directive='db'):
        lines.append(label + ':')
        for i in range(0, len(values), 16):
            lines.append('    ' + directive + ' ' + ','.join(map(str, values[i:i+16])))
    coefficients = []
    for a in range(256):
        theta = a * math.tau / 256
        scale = 0.72 + 0.32 * math.sin(2 * theta)
        coefficients.extend((round(256 * scale * math.cos(theta)),
                             round(256 * scale * math.sin(theta))))
    emit('transforms', coefficients, 'dw')
    emit('tex_rows', [(i & 63) * 64 for i in range(256)], 'dw')
    emit('texture', [texture_pixel(x, y) for y in range(64) for x in range(64)])
    for name, bit in [('b', 1), ('r', 2), ('g', 4)]:
        emit('lut_' + name, [(240 if (i >> 3) & bit else 0) |
                            (15 if i & bit else 0) for i in range(64)])
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    Path(__file__).with_name('assets.inc').write_text(generate(), encoding='ascii')
